version: '3.9'

services:
  logstash:
    container_name: logstash
    build:
       context: logstash/conf/
       no_cache: true
    hostname: logstash_container
    mem_limit: 4G
    mem_reservation: 4G
    cpus: 2.0
    volumes:
      - ./logstash/conf/jvm.options:/usr/share/logstash/config/jvm.options:ro
      - ./logstash/conf/startup.options:/usr/share/logstash/config/startup.options:ro
      - ./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/cisa-cveids-dcr-sentinel.conf:/usr/share/logstash/pipeline/cisa-cveids-dcr-sentinel.conf:ro
      - ./logstash/files/cisa_cve_cronjob.sh:/usr/share/logstash/cisa_cve_cronjob.sh:ro
      - ./logstash/files/cisa_cve_compact_json.py:/usr/share/logstash/cisa_cve_compact_json.py:ro
      - logstash-volume:/usr/share/logstash
    ports:
      - 5044:5044
      - 5514:5514/udp
      - 5514:5514/tcp
      - 9600:9600
    restart: unless-stopped
    command: /usr/share/logstash/cisa_cve_cronjob.sh

volumes:
  logstash-volume:
    driver: local
